
- name: 'Create VM Cluster Network {{ vm_cluster_network_name }}'
  oci_database_vm_cluster_network:
    compartment_id: '{{ compartment_id }}'
    defined_tags: '{{ vm_cluster_network_defined_tags }}'
    display_name: '{{ vm_cluster_network_name }}'
    dns: '{{ vm_cluster_network_dns }}'
    exadata_infrastructure_id: '{{ exadata_infrastructure_id }}'
    freeform_tags: '{{ vm_cluster_network_freeform_tags }}'
    #key_by: ['exadata_infrastructure_id', 'display_name'] 
    ntp: '{{ vm_cluster_network_ntp }}'
    scans:
    - hostname: '{{ vm_cluster_network_scan_hostname }}'
      port: '{{ vm_cluster_network_port }}'
      ips: ['{{ scan_ip_1 }}', '{{ scan_ip_2 }}', '{{ scan_ip_3 }}']
    vm_networks:
    - domain_name: '{{ client_domain_name }}'
      gateway: '{{ client_gateway }}'
      netmask: '{{ client_netmask }}'
      network_type: 'CLIENT'
      nodes: '{{ client_nodes }}'
      vlan_id: '{{ client_vlan_id }}'
    - domain_name: '{{ backup_domain_name }}'
      gateway: '{{ backup_gateway }}'
      netmask: '{{ backup_netmask }}'
      network_type: 'BACKUP'
      nodes: '{{ backup_nodes }}'
      vlan_id: '{{ backup_vlan_id }}'
  register: vm_cluster_network_create_result
- debug:
    msg: '{{ vm_cluster_network_create_result }}'
- set_fact:
    vm_cluster_network_id: '{{ vm_cluster_network_create_result.vm_cluster_network.id }}'
