
# Set-Up Exadata Cloud@Customer Infrastructure

- name: 'Check Exadata Type variable.'
  assert:
    that:
      - exadata_type is defined and exadata_type == 'exacc'
    fail_msg: 'Define variable exadata_type to be exacc.'

- name: Create ExaCC VM Cluster Network
  include_tasks: exacc_create_vm_cluster_network.yml
  when:
       - action == 'create_vm_cluster_network'

- name: Create ExaCC VM Cluster
  include_tasks: exacc_create_vm_cluster.yml
  when:
       - action == 'create_vm_cluster'

- name: Fetch ExaCC VM Cluster Network
  include_tasks: exacc_vm_cluster_network_discovery.yml
  when:
       - action == 'fetch_vm_cluster_network' 

- name: Fetch ExaCC VM Cluster 
  include_tasks: exacc_vm_cluster_discovery.yml
  when:
       - action == 'fetch_vm_cluster'

- name: Delete ExaCC VM Cluster
  include_tasks: exacc_delete_vm_cluster.yml
  when:
       - action == 'delete_vm_cluster'

     
